Vagrant.configure("2") do |config|
    config.vm.box = "centos/7"
    config.vm.hostname = "sonarqube"
    config.vm.network 'forwarded_port', guest: 9000, host: 9000, host_ip: '127.0.0.1'
    config.vm.network "private_network", ip: "192.168.52.6"
    config.vm.provision "shell", path: "provision.sh"
    config.vm.provider "vmware_desktop" do |v|
      v.vmx["memsize"] = "1024"
      v.vmx["numvcpus"] = "2"
    end
  end